name: Release

on:
  push:
    tags:
      - "v*.*.*"

env:
  BIN_NAME: envloader

jobs:
  build:
    name: Build & Upload Binaries
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-musl
          - aarch64-unknown-linux-musl
        include:
          - target: x86_64-unknown-linux-musl
            arch: x86_64
          - target: aarch64-unknown-linux-musl
            arch: arm64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y musl-tools

      - name: Install Rust target
        run: rustup target add ${{ matrix.target }}

      - name: Build binary
        run: cargo build --release --target ${{ matrix.target }}

      - name: Rename binary
        run: |
          mkdir -p dist
          cp target/${{ matrix.target }}/release/${{ env.BIN_NAME }} dist/${{ env.BIN_NAME }}-${{ matrix.arch }}

      - name: Upload release binaries
        uses: softprops/action-gh-release@v1
        with:
          files: dist/${{ env.BIN_NAME }}-${{ matrix.arch }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
